version: '3'

services:
  node-server:
    build: 
      dockerfile: ./Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app

  node-test:
    build: 
      dockerfile: ./Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    command: npm run test